* Карточка с пропусками
{{cid::Ответ::Комментарий}}

* Теория вероятностей и статистика
 :PROPERTIES:
  :ANKI_DECK: Теория вероятностей
 :END:

** Перестановки 1
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1669710575415
  :END:
*** Текст

{{c1::Перестановками::...}} называют комбинации, состоящие из одних и тех
же n различных элементов и отличающиеся порядком их расположения.
*** Дополнительно


** Перестановки 2
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669736128770
   :END:
*** Текст
Перестановками называют {{c1::комбинации, состоящие из одних и тех
же n различных элементов и отличающиеся порядком их расположения::...}}.

*** Дополнительно

** Перестановки 3
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669736353767
   :END:
*** Текст

$$ P_n = {{c1::n!::...}} $$

*** Дополнительно


** Перестановки 4
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669738466218
   :END:
*** Текст

$$ {{c1::P_n::...}} = n! $$

*** Дополнительно

** Перестановки 5
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669738466373
   :END:
*** Текст

$$  n! = {{c1::1 \cdot 2 \cdot 3 \cdot \dots \cdot n::...}} $$

*** Дополнительно


** Перестановки 6
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669741999481
   :END:
*** Текст

$$  0! = {{c1::1::...}} $$

*** Дополнительно


** Размещения 1
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669741999662
   :END:
*** Текст

{{c1::Размещениями::...}} называются комбинации, составленные из $n$ различных элементов по $k$ элементов, которые отличаются либо составом элементов,
либо их порядком. (Порядок имеет значение)

{1, 2, 3} != {2, 1, 3}

*** Дополнительно
Каждое упорядоченное $k$ - элементное подмножество $n$ - элементного множества называется размещением n по k элементам.(Второй термин, некоторым более знакомым)


** Размещения 2
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669741999823
   :END:
*** Текст

Размещениями называются {{c1::комбинации, составленные из $n$ различных элементов по $k$ элементов, которые отличаются либо составом элементов,
либо их порядком. (Порядок имеет значение) ::...}}

{1, 2, 3} != {2, 1, 3}

*** Дополнительно
Каждое упорядоченное $k$ - элементное подмножество $n$ - элементного множества называется размещением $n$ по $k$ элементам.(Второй термин, некоторым более знакомым)

** Размещения 3
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669742415192
   :END:
*** Текст

$$A^k_n = {{c1::\frac{n!}{(n-k)!}::...}}$$

** Размещения 4
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669742415377
   :END:
*** Текст

$${{c1::A^k_n::...}} = \frac{n!}{(n-k)!}$$


*** Дополнительно

** Сочетания 1
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669742000005
   :END:
*** Текст

{{c1::Сочетаниями::...}} называются комбинации, составленные из n различных элементов по m элементов, которые отличаются хотя бы одним элементов. (Порядок не имеет значение)

{1, 2, 3} = {2, 1, 3}
*** Дополнительно

** Сочетания 2
   :PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669742000164
   :END:
*** Текст

Сочетаниями называются {{c1::комбинации, составленные из n различных элементов по m элементов, которые отличаются хотя бы одним элементов.
(Порядок не имеет значение)::...}}

{1, 2, 3} = {2, 1, 3}

*** Дополнительно


** Сочетания 3
:PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669742770644
   :END:
*** Текст

$$C^k_n = {{c1::\frac{n!}{k!(n-k)!}::...}}$$

*** Дополнительно


** Сочетания 4
:PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :ANKI_NOTE_ID: 1669742770834
   :END:
*** Текст

$${{c1::C^k_n::...}} = \frac{n!}{k! ( n-k )!}$$

*** Дополнительно


** Правило произведения 1
:PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :END:
*** Текст

Если существует $n$ вариантов выбора первого элемента и для каждого из них имеется $m$ вариантов выбора второго элемента, 
то всего существует {{c1::$n \cdot m$::...}} различных пар с выбранными таким образом первым и вторым элементом.

*** Дополнительно

** Правило произведения 1
:PROPERTIES:
   :ANKI_NOTE_TYPE: С пропусками
   :END:
*** Текст

Если существует {{c1::$n$ вариантов выбора первого элемента и для каждого из них имеется $m$ вариантов выбора второго элемента::...}}, 
то всего существует $n \cdot m$ различных пар с выбранными таким образом первым и вторым элементом.

*** Дополнительно
